const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.join(__dirname, '..');
const source = ['clothing-manifest.js', 'state.js'].map(file => fs.readFileSync(path.join(root, 'js', file), 'utf8')).join('\n');
const api = vm.runInNewContext(source + '\n({defaultWardrobe, normalizeWardrobe, CLOTHING_CATALOG})');
const fresh = api.defaultWardrobe();
assert.equal(Object.keys(fresh.owned.superior).length, 0);
assert.equal(fresh.owned.accesorios.anteojos_redondos, undefined);
const legacy = {owned: {superior: {conjunto1_superior: true}}, equipped: {superior: 'conjunto1_superior'}, betaWelcomeClaimed: true};
const migrated = api.normalizeWardrobe(legacy);
assert.equal(migrated.equipped.superior, 'conjunto1_superior');
assert.equal(migrated.owned.superior.remera_celeste, undefined);
assert.equal(migrated.betaWelcomeClaimed, true);
assert.equal(legacy.owned.superior.remera_celeste, undefined);
const saved = api.normalizeWardrobe({ ...fresh, equipped: {superior: 'buzo_coral', accesorios: 'anteojos_redondos', inferior: 'invalid'} });
assert.equal(saved.equipped.superior, null);
assert.equal(saved.equipped.accesorios, null);
assert.equal(saved.equipped.inferior, null);
assert(!Object.values(api.CLOTHING_CATALOG).flat().some(item => item.setId === 'vestidor44'));
console.log('Vestidor: prendas anteriores conservadas y colección retirada de los guardados.');
